# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_repo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('repo', models.CharField(max_length=255, unique=True)),
                ('secret_key', models.CharField(max_length=29, unique=True)),
                ('token', models.CharField(max_length=1200, unique=True)),
                ('token_algo', models.CharField(default='HS256', max_length=10)),
            ],
        ),
    ]
