# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-26 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNameCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_job_name', models.CharField(max_length=255, unique=True)),
                ('job_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=255)),
                ('git_repo', models.CharField(max_length=255)),
                ('job_name', models.CharField(max_length=255, unique=True)),
                ('deterministic', models.BooleanField()),
            ],
        ),
    ]
