# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-27 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_jobnamecounter_jobspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobspec',
            name='deterministic',
            field=models.NullBooleanField(),
        ),
    ]
