# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialApp', '0002_group_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('py', 'Python 2 (.py)'), ('py3', 'Python 3 (.py)'), ('pl', 'Perl (.pl)'), ('java', 'Java (.java)'), ('c', 'C [code] (.c)'), ('h', 'C [header] (.h)'), ('cpp', 'C++ [code] (.cpp)'), ('hpp', 'C++ [header] (.hpp)'), ('js', 'Javascript (.js)'), ('css', 'CSS (.css)'), ('html', 'HTML (.html)'), ('php', 'PHP (.php)'), ('rb', 'Ruby (.rb)'), ('sh', 'Shell Script (.sh)'), ('go', 'Go (.go)'), ('hs', 'Haskell (.hs)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialApp.Person')),
                ('owning_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialApp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialApp.Group')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryPersonMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialApp.Person')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Repository'),
        ),
    ]
