# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BackendAuthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BackendAuthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BackendNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=255)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Backend')),
            ],
        ),
        migrations.CreateModel(
            name='BackendTokenAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('auth_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthData')),
            ],
        ),
        migrations.CreateModel(
            name='BackendType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BackendUserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('auth_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthData')),
            ],
        ),
        migrations.CreateModel(
            name='GitBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('auth_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthData')),
                ('authentication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthType')),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Backend')),
            ],
        ),
        migrations.CreateModel(
            name='GitLabBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('auth_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthData')),
                ('authentication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthType')),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Backend')),
            ],
        ),
        migrations.CreateModel(
            name='GitRepoGitLabAssociations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.GitLabBackend')),
                ('gitrepo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.GitBackend')),
            ],
        ),
        migrations.CreateModel(
            name='MongoBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=255)),
                ('backend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideApp.Backend')),
            ],
        ),
        migrations.AddField(
            model_name='backendauthdata',
            name='auth_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendAuthType'),
        ),
        migrations.AddField(
            model_name='backend',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.BackendType'),
        ),
    ]
