# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideApp', '0002_auto_20170919_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(choices=[('ot', 'Otro'), ('py', 'Python 2 (.py)'), ('py3', 'Python 3 (.py)'), ('pl', 'Perl (.pl)'), ('java', 'Java (.java)'), ('c', 'C [code] (.c)'), ('h', 'C [header] (.h)'), ('cpp', 'C++ [code] (.cpp)'), ('hpp', 'C++ [header] (.hpp)'), ('js', 'Javascript (.js)'), ('css', 'CSS (.css)'), ('html', 'HTML (.html)'), ('php', 'PHP (.php)'), ('rb', 'Ruby (.rb)'), ('sh', 'Shell Script (.sh)'), ('go', 'Go (.go)'), ('hs', 'Haskell (.hs)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialApp.Person'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owning_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialApp.Group'),
        ),
    ]
