# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideApp', '0003_auto_20171231_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programing_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.ProgramingLanguage')),
                ('related_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideApp.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideApp.RepositoryTemplate'),
        ),
    ]
