# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideApp', '0005_auto_20180128_1827'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='programinglanguage',
        #     name='name',
        #     field=models.CharField(max_length=100, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='repositorytemplate',
        #     name='related_repository',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideApp.Repository'),
        # ),
    ]
