# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideApp', '0006_auto_20180128_1903'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='repositorytemplate',
        #     name='repository_url',
        #     field=models.CharField(default='http://10.10.10.1/', max_length=255, unique=True),
        #     preserve_default=False,
        # ),
    ]
