# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assignmentGradeWeight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('relativeGradeWeight', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categoryGradeWeight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('relativeGradeWeight', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subcategoryGradeWeight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('relativeGradeWeight', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('academicCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.AcademicCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomGradeWeight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('relativeGradeWeight', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.Classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialApp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classSubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academicApp.ClassSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.Course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.Section'),
        ),
        migrations.AddField(
            model_name='academiccategory',
            name='classroomTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.ClassroomTeacher'),
        ),
        migrations.AddField(
            model_name='academicassignment',
            name='academicSubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.AcademicSubCategory'),
        ),
    ]
