# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 15:22
from __future__ import unicode_literals

from django.db import migrations

from authApp import models


def fill_auth_types(apps, schema_editor):
    auth_type = models.AuthenticationType
    classic = auth_type(name="Clasica")
    classic.save()
    lti = auth_type(name="LTI")
    lti.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_authenticationtype_userauthentication'),
    ]

    operations = [
        migrations.RunPython(fill_auth_types),
    ]
