# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='secret_key',
            field=models.CharField(max_length=29, unique=True),
        ),
    ]
