# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20171112_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
