# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20171112_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='edit_date_in_token',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='token_algo',
            field=models.CharField(default='HS256', max_length=10),
        ),
    ]
