apiVersion: v1
kind: Pod
metadata:
        name: utility-2
spec:
        containers:
        - image: debian:latest
          command:
                  - sleep
                  - "30"
          name: utility-2

