# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignmentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('academicAssignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.AcademicAssignment')),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.ClassroomStudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCategoryGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('academicCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.AcademicCategory')),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.ClassroomStudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubCategoryGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('academicSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.AcademicSubCategory')),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicApp.ClassroomStudent')),
            ],
        ),
    ]
